#%RAML 1.0
title: BackBase-Demo-Login
description: Simple Login in BackBase
version: v1
baseUri: "{version}"
mediaType: application/json
protocols: HTTP
traits:
   logged:
      usage: Se aplica cuando se requiere identificar al usuario mediante un id de sesion 
      headers:
         sessionID:
            description: Token para identificar al usuario en la peticiones
            example: 12decfr34e
            required: true

types:
   User: !include types/login/User.json
   Account: !include types/accounts/Account.json
   AccountList: !include types/accounts/AccountList.json
   Response20X: !include types/Response20X.json
   Response40X: !include types/Response40X.json
   Response50X: !include types/Response50X.json

/login:
   displayName: Validacion de usuario
   description: Se ingresa usuario y password
   get:
      description: Valida usuario y password.
      body:
         type: User
         example: !include data/login/formUser.json
      responses:
         200:
            headers:
               sessionId:
                  type: string
                  example: 12decfr34e
            description: Validación de credenciales correcta
            body:
               type: Response20X
               example: !include responses/login/Response20X-Access.json
   post:
      description: Valida usuario y password.
      body:
         type: User
         example: !include data/login/formUser.json
      responses:
         200:
            headers:
               sessionId:
                  type: string
                  example: 12decfr34e
            description: Validación de credenciales correcta
            body:
               type: Response20X
               example: !include responses/login/Response20X-Access.json
      #    401:
      #       description: No cuenta con credenciales de autenticación válidas
      #       body:
      #          type: Response40X
      #          example: !include responses/login/Response40X-InvalidCredentials.json
      #    403:
      #       description: Existe una sesión activa.
      #       body:
      #          type: Response40X
      #          example: !include responses/login/Response40X-ActiveSession.json
      #    500:
      #       description: Internal Server Error
      #       body:
      #          type: Response50X
      #          example: !include responses/500.json

/logout:
   displayName: Cierra la sesión del usuario
   post:
      is: [ logged ]
      responses:
         200:
            body:
               type: Response20X
               example: !include responses/login/Response20X-logout.json

/accounts:
   description: Lista de cuentas del usuario
   get:
      description: obtener la lista de cuentas del usuario
      is: [ logged ]
      responses:
         200:
            body:
               application/json:
                  type: AccountList
                  example: !include responses/accounts/AccountListResponse.json
   /{accountId}:
      description: Cuenta especifica del usuario
      get:
         description: obtener una cuenta especifica del usuario
         is: [ logged ]
         responses:
            200:
               body:
                  application/json:
                     type: Account
                     example: !include responses/accounts/AccountResponse.json
