#%RAML 1.0
title: Customers
version: v1
baseUri: "/{version}"

# --------------------------------------
#   My Accounts
# --------------------------------------

/customers:
  displayName: All the customers
  get:
    responses:
      200:
        body:
          application/json:
            example:
              !include customers.json
